spring.application.name=FoodFleet

spring.datasource.url=jdbc:postgresql://localhost:5432/foodfleet
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


